version: '3.7'
services:
  mysql:       
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    networks:
      - spring-boot-mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productsdb    
    container_name: products-db

networks:
    spring-boot-mysql-network:
        driver: bridge